@startuml

package "大会組織" {
  Entity "組織種別" as OrganizationType {
    組織種別CD[PK]
    --
    種別名
  }

  Entity "地域マスタ" as Region {
    地域CD[PK]
    --
    地域名
  }

  Entity "組織マスタ" as Organization {
    組織CD[PK]
    --
    正式名称
    通称名
    管轄地域CD[FK]
    組織種別CD[FK]
  }
}

Package "クラブチーム" {
  Entity "チームマスタ" as Team {
    所属組織CD[PK, FK]
    チームCD[PK]
    --
    チーム名
    ホームスタジアムCD[FK]
  }

  Entity "メンバー履歴" as MemberHistory {
    選手CD[PK, FK]
    所属組織CD[PK, FK]
    チームCD[PK, FK]
    --
    加入日時
    退席日時
  }
}

Package "メンバー" {
  Entity "メンバー" as Member {
    選手CD[PK]
    --
    選手名
    生年月日
    身長
    体重
    出生地域CD[FK]
    メインポジション
    現役フラグ
  }
}

Package "施設" {
  Entity "スタジアム" as Stadium {
    スタジアムCD[PK]
    --
    スタジアム名称
    所在地
    収容人数
  }
}

Package "大会関連" {
  Entity "大会マスタ" as Tournament {
    所属組織CD[PK, FK]
    大会CD[PK]
    --
    通称名
  }

  Entity "開催大会情報" as TournamentInfo {
    開催大会情報ID[PK]
    --
    所属組織CD[FK]
    大会CD[FK]
    開催回数
    正式名称
    所属チーム数
    全ステージ数
    開始年月
    終了年月
    表示用の開催年度
    大会方式
    ホームアウェイ方式
    延長フラグ
    PKフラグ
    交代人数
  }

  Entity "大会参加チームテーブル" as SeaSonTournament {
    開催大会情報ID[PK]
    -- 
    チームCD[FK]
  }

  Entity "節別チームテーブル" as MatchDayRank {
    リーグID[PK,FK]
    チームCD[PK,FK]
    節[PK]
    --
    順位
    勝ち点
    試合数
    勝ち数
    引き分け数
    負け数
    得点数
    失点数
    得失点差  
  }

  Entity "トーナメント表構造" as TournamentTable {
    トーナメントID[PK]
    --
    開催大会情報ID[FK]
    ステージ
    ラウンド
    マッチNo.
    次のマッチNo.
  }

  Entity "リーグ表構造" as LeagueTable {
    リーグID[PK]
    --
    開催大会情報ID[FK]
    グループ名
  }

  Entity "別大会への条件ルール" as TournamentDetail {
    開催大会情報ID[PK,FK]
    ルール連番ID[PK]
    --
    別大会の所属組織CD[FK]
    別大会CD[FK]
    別大会の参加年度
    条件名
    順位_to
    順位_from
  }
}

Package "試合関連" {
  Entity "試合" as Match {
    試合ID
    --
    リーグID
    トーナメントID
    ラウンド
    ホームチームCD
    ホームチーム合計得点
    ホームチームの前半得点
    ホームチームの後半得点
    ホームチームの延長前半得点
    ホームチームの延長後半得点
    ホームチームのPKスコア
    アウェイチームCD
    アウェイチーム合計得点
    アウェイチームの前半得点
    アウェイチームの後半得点
    アウェイチームの延長前半得点
    アウェイチームのPKスコア
    開始日時
  }

  Entity "試合イベント" as MatchEvent {
    試合ID
    イベントID
    --
    イベント発生時の規定経過時間
    イベント発生時のAT経過時間
    イベント種別CD
    チームCD
    メインターゲット選手CD
    関連イベントID
  }

  Entity "イベント種別マスタ" as EventCategory {
    イベント種別CD
    --
    イベント名
  }

  Entity "試合ラインナップ" as MatchLineup {
    試合ID
    チームCD
    選手CD
    --
    役割
    ポジション
    スターティングフラグ
    インタイム
    アウトタイム
    背番号
    得点
    PK
    アシスト
    シュート数
    警告
    退場
  }

  Entity "試合スタッツ" as MatchStats {
    試合ID
    選手CD
    --
    スタッツ役割CD
    スタッツ結果
  }

  Entity "スタッツ種別" as StatsCategory {
    スタッツ役割CD
    --
    スタッツ名
  }

  Entity "試合詳細" as MatchInfo {
    試合ID
    --
    観客数
    芝状態
    天候
    気温
    湿度
    風
    スタジアムCD
  }

  Entity "試合主審テーブル" as MatchReferee {
    試合ID
    試合連番ID
    --
    レフェリーID
    審判ロールID
  }
}

Package "主審" {
  Entity "審判ロール" as RefereeRole {
    審判ロールID
    --
    役割
  }

  Entity "レフェリーマスター" as Referee {
    レフェリーID
    --
    名前
    組織CD
    資格
    適用開始日
    適用終了日
  }
}

OrganizationType  ||-l-{ Organization
Region ||-r-o{ Organization
Organization ||--o{ Team
Stadium ||-u-|| Team
Team ||-r-{ MemberHistory
Member ||-l-{ MemberHistory

@enduml